# Generated by Django 5.0.2 on 2024-02-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='persentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
