# Generated by Django 5.0.1 on 2024-05-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='years',
            field=models.CharField(max_length=10),
        ),
    ]
