# Generated by Django 5.0.1 on 2024-05-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactme',
            options={'verbose_name_plural': 'Contact Me'},
        ),
    ]
